###
POST http://localhost:5000/api/user/createuser HTTP/1.1
Content-Type: application/json

{
    "username":"susheelthapa",
    "password":"susheelthapa"
}

###
POST http://localhost:5000/api/user/getuser HTTP/1.1
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoic3VzaGVlbHRoYXBhIiwicGFzc3dvcmQiOiJzdXNoZWVsdGhhcGEifSwiaWF0IjoxNjcyNDA4MzcxLCJleHAiOjE2NzI0MzgzNzF9.JntTJH_otHrc1RSfNGhnYG7p8cgXbTQi_rKizwAvkp0"
}