###
GET http://localhost:6000/ HTTP/1.1

###
POST http://localhost:6000/login HTTP/1.1
Content-Type: application/json

{
    "email":"susheelthapa@outlook.com",
    "password":"123456789",
    "isAdmin":"true"
}

###
POST http://localhost:6000/profile HTTP/1.1
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoic3VzaGVlbHRoYXBhQG91dGxvb2suY29tIiwicGFzc3dvcmQiOiIxMjM0NTY3ODkiLCJpc0FkbWluIjoidHJ1ZSJ9LCJpYXQiOjE2NzIwNjE2NjcsImV4cCI6MTY3MjA5MTY2N30.Q0Leb2uBb1JJnG6lBkHOVzP1_HlZs_5ghRdBt2uuCM8"
}