### SIGNUP DETAILS
POST http://localhost:5000/api/signup/ HTTP/1.1
Content-Type: application/json

{
    "username":"susheelthapa",
    "password":"susheelthapa",
    "email":"077bct090.susheel@pcampus.edu.np",
    "phone":"+9779816227392"
}

### LOGIN DETAILS
POST http://localhost:5000/api/login HTTP/1.1
Content-Type: application/json

{
    "username":"susheelthapa",
    "password":"susheelthapa"
}



### GET USER OF PROVIDED USER ID
GET http://localhost:5000/api/users/63b47f77eb756f6c83b4129f HTTP/1.1

### GET LIST OF ALL THE USER
GET http://localhost:5000/api/users HTTP/1.1



### GET ASSET OF PROVIDED ASSET ID
GET http://localhost:5000/api/assets/63b47f77eb756f6c83b412a6 HTTP/1.1

### GET LIST OF ALL THE ASSETS
GET http://localhost:5000/api/assets/ HTTP/1.1



### GET LIST OF ALL THE COLLEGES
GET http://localhost:5000/api/colleges HTTP/1.1

### GET COLLEGE OF PROVIDED COLLEGE ID
GET http://localhost:5000/api/colleges/63b47f77eb756f6c83b412ab HTTP/1.1


### GET THE LIST OF TAGS 
GET http://localhost:5000/api/tags

### BOOKING ASSETS BY USER
POST http://localhost:5000/api/users/bookassets HTTP/1.1
Content-Type: application/json

{
    "userId":"63b42453502372f0100bdf55",
    "bookedAssets":[
        {
            "asset":"63b47f77eb756f6c83b412a4",
            "bookedQuantities":"1"
        },
        {
            "asset":"63b47f77eb756f6c83b412a6",
            "bookedQuantities":"1"
        }
    ]
}

